services:
  db:
    image: cockroachdb/cockroach:v25.2.4
    container_name: cockroachdb
    command: start-single-node --insecure --store=/cockroach/cockroach-data --http-port=8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      - COCKROACH_MAX_OFFSET=500ms

  backend:
    build:
      context: ./backend
    container_name: flask-backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./nepeto-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - ./nepeto-frontend/.env

volumes:
  cockroach-data:
