services:
  db:
    image: cockroachdb/cockroach:v25.2.4
    container_name: cockroachdb
    command: start-single-node --insecure --store=/cockroach/cockroach-data --http-port=8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      - COCKROACH_MAX_OFFSET=500ms

  backend:
    build: .
    container_name: flask-backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}

volumes:
  cockroach-data:
