version: "3.8"

services:
  db:
    image: cockroachdb/cockroach:v25.2.4
    container_name: cockroachdb
    command: start-single-node --insecure --store=/cockroach/cockroach-data
    ports:
      - "26257:26257"  # SQL port
      - "8080:8080"    # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  db-init:
    image: cockroachdb/cockroach:v25.2.4
    depends_on:
      - db
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 5
        cockroach sql --insecure --host=db -e "CREATE DATABASE IF NOT EXISTS nepeto_exercise;"

volumes:
  cockroach-data:
